# Generated by Django 5.1 on 2024-08-09 20:19

import ckeditor.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Başlıq')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Lifestyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Başlıq')),
                ('autor', models.CharField(blank=True, max_length=200, null=True, verbose_name='Müəllif')),
                ('img', models.URLField(verbose_name='Foto')),
                ('img2', models.URLField(blank=True, default='', null=True, verbose_name='Foto iç şəkil')),
                ('img3', models.URLField(blank=True, default='', null=True, verbose_name='Events üçün şəkil')),
                ('video', models.CharField(blank=True, default='', max_length=1000, null=True, verbose_name='Video')),
                ('txt', ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Məzmun')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarix')),
                ('bigsize', models.BooleanField(default=False, verbose_name='Yaşam tərzi')),
                ('bigsize2', models.BooleanField(default=False, verbose_name='Başlıq üçün birinci')),
                ('bigsize3', models.BooleanField(default=False, verbose_name='Başlıq üst')),
                ('bigsize4', models.BooleanField(default=False, verbose_name='Başlıq alt')),
                ('bigsize5', models.BooleanField(default=False, verbose_name='Events')),
                ('bigsize6', models.BooleanField(default=False, verbose_name='Seçilmiş məqalə')),
                ('slug', models.SlugField(default='time_person', max_length=255, unique=True, verbose_name='URL')),
                ('category', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='articles.categories', verbose_name='Bölmə')),
            ],
            options={
                'verbose_name': 'Məqalə',
                'verbose_name_plural': 'Məqalələr',
            },
        ),
    ]
