# Generated by Django 5.1 on 2024-08-09 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lifestyle',
            new_name='Articles',
        ),
    ]
