# Generated by Django 5.1 on 2024-08-11 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_rename_lifestyle_articles'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='name_az',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_en',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='categories',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Başlıq'),
        ),
    ]
