# Generated by Django 5.1 on 2024-08-11 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_categories_name_az_categories_name_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='name_az',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='articles',
            name='name_en',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Başlıq'),
        ),
        migrations.AddField(
            model_name='articles',
            name='name_ru',
            field=models.CharField(max_length=200, null=True, unique=True, verbose_name='Başlıq'),
        ),
    ]
