# Generated by Django 5.1 on 2024-08-11 02:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_articles_name_az_articles_name_en_articles_name_ru'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='bigsize',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='bigsize2',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='bigsize3',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='bigsize4',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='bigsize5',
        ),
        migrations.RemoveField(
            model_name='articles',
            name='bigsize6',
        ),
    ]
