# Generated by Django 5.1 on 2024-08-11 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_remove_articles_bigsize_remove_articles_bigsize2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='autor_az',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Müəllif'),
        ),
        migrations.AddField(
            model_name='articles',
            name='autor_en',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Müəllif'),
        ),
        migrations.AddField(
            model_name='articles',
            name='autor_ru',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Müəllif'),
        ),
    ]
