# Generated by Django 5.1 on 2024-08-11 02:14

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_articles_autor_az_articles_autor_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='txt_az',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='articles',
            name='txt_en',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Məzmun'),
        ),
        migrations.AddField(
            model_name='articles',
            name='txt_ru',
            field=ckeditor.fields.RichTextField(blank=True, default='', null=True, verbose_name='Məzmun'),
        ),
    ]
