# Generated by Django 5.1 on 2024-08-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_articles_txt_az_articles_txt_en_articles_txt_ru'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='slide',
            field=models.BooleanField(default=False, verbose_name='Orta Karusel'),
        ),
        migrations.AddField(
            model_name='articles',
            name='txt_desc',
            field=models.TextField(default='', verbose_name='Qısa məzmun'),
        ),
    ]
