# Generated by Django 5.1 on 2024-08-11 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0008_articles_slide_articles_txt_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='txt_desc_az',
            field=models.TextField(default='', null=True, verbose_name='Qısa məzmun'),
        ),
        migrations.AddField(
            model_name='articles',
            name='txt_desc_en',
            field=models.TextField(default='', null=True, verbose_name='Qısa məzmun'),
        ),
        migrations.AddField(
            model_name='articles',
            name='txt_desc_ru',
            field=models.TextField(default='', null=True, verbose_name='Qısa məzmun'),
        ),
    ]
