# Generated by Django 5.1 on 2024-08-12 04:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_articles_txt_desc_az_articles_txt_desc_en_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarix'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='txt_desc',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Qısa məzmun'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='txt_desc_az',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Qısa məzmun'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='txt_desc_en',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Qısa məzmun'),
        ),
        migrations.AlterField(
            model_name='articles',
            name='txt_desc_ru',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Qısa məzmun'),
        ),
    ]
