# Generated by Django 5.1 on 2024-08-12 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0010_categories_date_alter_articles_txt_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='navbar',
            field=models.BooleanField(default=False, verbose_name='Kəllə'),
        ),
    ]
