# Generated by Django 5.1 on 2024-08-12 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0015_remove_categories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default='time_person', max_length=255, unique=True, verbose_name='URL'),
        ),
    ]
