# Generated by Django 5.1 on 2024-08-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0016_categories_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='slide2',
            field=models.BooleanField(default=False, verbose_name='Cover Karusel'),
        ),
        migrations.AddField(
            model_name='articles',
            name='slide3',
            field=models.BooleanField(default=False, verbose_name="EDITOR'S PICKS"),
        ),
    ]
