# Generated by Django 5.1 on 2024-08-13 19:59

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0017_articles_slide2_articles_slide3'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', ckeditor.fields.RichTextField(verbose_name='Haqqımızda')),
                ('txt_az', ckeditor.fields.RichTextField(null=True, verbose_name='Haqqımızda')),
                ('txt_en', ckeditor.fields.RichTextField(null=True, verbose_name='Haqqımızda')),
                ('txt_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Haqqımızda')),
            ],
            options={
                'verbose_name': 'Haqqımızda',
                'verbose_name_plural': 'Haqqımızda',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', ckeditor.fields.RichTextField(verbose_name='Əlaqə')),
                ('txt_az', ckeditor.fields.RichTextField(null=True, verbose_name='Əlaqə')),
                ('txt_en', ckeditor.fields.RichTextField(null=True, verbose_name='Əlaqə')),
                ('txt_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Əlaqə')),
            ],
            options={
                'verbose_name': 'Əlaqə',
                'verbose_name_plural': 'Əlaqə',
            },
        ),
        migrations.CreateModel(
            name='Partnors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Ad')),
                ('img', models.URLField(default='', verbose_name='Foto')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tarix')),
            ],
            options={
                'verbose_name': 'Partnorlar',
                'verbose_name_plural': 'Partnorlar',
            },
        ),
    ]
