# Generated by Django 5.1 on 2024-08-14 19:23

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0018_about_contact_partnors'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutinFooter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('txt', ckeditor.fields.RichTextField(verbose_name='Sonluq')),
                ('txt_az', ckeditor.fields.RichTextField(null=True, verbose_name='Sonluq')),
                ('txt_en', ckeditor.fields.RichTextField(null=True, verbose_name='Sonluq')),
                ('txt_ru', ckeditor.fields.RichTextField(null=True, verbose_name='Sonluq')),
            ],
            options={
                'verbose_name': 'Sonluq',
                'verbose_name_plural': 'Sonluq',
            },
        ),
    ]
