# Generated by Django 5.1 on 2024-08-15 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0020_articles_img4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='img4',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Cover Karusel üçün şəkil - mobil'),
        ),
    ]
