# Generated by Django 5.1 on 2024-08-16 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_alter_articles_img4'),
    ]

    operations = [
        migrations.AddField(
            model_name='articles',
            name='img5',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Cover Karusel üçün şəkil - web'),
        ),
    ]
