# Generated by Django 5.1 on 2024-08-17 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0022_articles_img5'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutinfooter',
            name='txt',
            field=models.TextField(verbose_name='Sonluq'),
        ),
        migrations.AlterField(
            model_name='aboutinfooter',
            name='txt_az',
            field=models.TextField(null=True, verbose_name='Sonluq'),
        ),
        migrations.AlterField(
            model_name='aboutinfooter',
            name='txt_en',
            field=models.TextField(null=True, verbose_name='Sonluq'),
        ),
        migrations.AlterField(
            model_name='aboutinfooter',
            name='txt_ru',
            field=models.TextField(null=True, verbose_name='Sonluq'),
        ),
    ]
